### ISSUE TITLE
.gitignore /target/?

### ISSUE THREAD

**Issue by felixrabe** [stopachka/risp#1]
You might want to remove the `target` directory and add

```
/target/
```

to your [.gitignore](https://github.com/stopachka/risp/blob/747cd91b71a1f6da31af248e776c47decd29dc50/.gitignore).

**Comment by stopachka** [comment]
thanks @felixrabe -- originally left target in so friends could try it even if they didn't have cargo. As this repo now has some followers though, makes sense clean it up and add /target/  to gitignore.
